### ISSUE TITLE
Update seed to work with MongoHQ

### ISSUE THREAD

**Issue by ecaron** [MongoHQ/seed#1]
Per a conversation with Kurt at MongoHQ:
> Seed needs to be brought up to date to work with 2.6.x (and potentially even our oplog users) before it will work out of the box against your DB.

This is because MongoHQ doesn't provide users access to "admin", and seed requires access to admin.

At present, seed works to push data INTO MongoHQ, but I think in being good stewards of data portability this library should be capable of pulling data FROM MongoHQ.

**Comment by nstott** [comment]
Cleaning up this issue, future work will carry on under the github.com/compose/transporter project
thanks!
